# Generated by Django 4.1.5 on 2023-01-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sku", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SKUDataMapping",
            fields=[
                ("sku", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sku.category"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sku.department"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sku.location"
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sku.subcategory",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="skumapping",
            name="dpt_loc_cat",
        ),
        migrations.DeleteModel(
            name="LocationDepartmentCategoryMapping",
        ),
        migrations.DeleteModel(
            name="SKUMapping",
        ),
    ]
